# Analyzing Toronto Neighborhoods

#### by Sushant Deshpande

# --------Week 1--------

## SEGMENT 1 : Define a problem or an idea

A group of investors would like to open a restaurant in Toronto but aren't sure which one to open and where to open. In this project, we'll use python's web scraping to get the postal codes for Torontoâ€™s neighborhoods, use the geographical coordinates provided to us in the last course and use FourSquare's API to get a list of nearby restaurants in a given locality.

We'll visualize the data using maps and bar charts. This will help us understand which type of restaurant is most popular in a given locality. With this information, investors can come to a decision.

## SEGMENT 2 : Describe the data

I started by getting the postal codes of Toronto from wikipedia using python's web scraping method. After that, I had to clean up the data and then merge the data with the geographical coordinate file provided to us in this course. Once I had all the postal codes with their corresponding geographical coordinates, the I leveraged the power of FourSquare to get a wealth of information.

FourSquare allowed me to get all the venues in my selected neighborhood. In this project, I only focused on East and West Toronto, but with FourSquare, the possibilities are unlimited. In the end, I had a clear picture of what is popular in which locality. With this knowledge, and investor and easily and quickly come to a decision as to where he wants to invest in in what.

# --------Week 2--------

### Still working on it...

In [4]:
from bs4 import BeautifulSoup
from collections import defaultdict
import requests
import csv
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from urllib.request import urlopen
%matplotlib inline
import numpy as np # library to handle data in a vectorized manner
import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import json # library to handle JSON files
#!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe
# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors
# import k-means from clustering stage
from sklearn.cluster import KMeans
#!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library
print('Libraries imported.')

Libraries imported.

In [29]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
tables = pd.read_html(url)
table_df = tables[0]
table_df.head()

  Postal Code         Community              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

In [31]:
table_df.columns = ['PostalCode', 'Borough', 'Neighborhood']
table_df.head()

  PostalCode           Borough               Neighborhood
0        M1A      Not assigned               Not assigned
1        M2A      Not assigned               Not assigned
2        M3A        North York                  Parkwoods
3        M4A        North York           Victoria Village
4        M5A  Downtown Toronto  Regent Park, Harbourfront

In [18]:
data7a = data6['Neighborhood'].fillna(data6['Borough'])
data7 = pd.DataFrame(data7a)
data6.columns = ['PostalCode', 'Borough', 'Neighborhood_1']
data8a = pd.concat([data6, data7], axis=1, sort=False)
data8b = data8a.drop(['Neighborhood_1'], axis=1)
data8 = data8b[:212]
data9a = data8.groupby('PostalCode')['Neighborhood'].apply(lambda x: ', '.join(x.astype(str))).reset_index()
data9b = data8.groupby('PostalCode')['Borough'].apply(lambda x: ', '.join(x.astype(str))).reset_index()
data9c = data9b['Borough'].str.split(', ').apply(set).str.join(', ')
data9d = pd.DataFrame(data9c)
data9d.head()

          Borough
0
1            NL\n
2             B\n
3   Scarborough\n
4   Scarborough\n

In [19]:
data9b.columns = ['PostalCode', 'Borough_1']
data9e = pd.concat([data9b, data9d], axis=1, sort=False)
data9f = data9e.drop(['Borough_1'], axis=1)
data9a.columns = ['PostalCode_1', 'Neighborhood']
data9g = pd.concat([data9f, data9a], axis=1, sort=False)
data9 = data9g.drop(['PostalCode_1'], axis=1)
data9.head()

,PostalCode,Borough,Neighborhood
0,\n,,
1,\n\n\nNL\n\nNS\n\nPE\n\nNB\n\nQC\n\nON\n\nMB\n...,NL\n,NS\n
2,A\n,B\n,C\n
3,M1B\n,Scarborough\n,Malvern
4,M1C\n,Scarborough\n,Rouge Hill

In [34]:
cor_df = pd.read_csv("Geospatial_Coordinates.csv")
cor_df.columns = ['PostalCode', 'Latitude', 'Longitude']
data_df = pd.merge(table_df, cor_df, on=['PostalCode'])
data_df[['Latitude', 'Longitude']] = data_df[['Latitude', 'Longitude']].astype(float)
data_df.head()

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494

In [45]:
address = 'Toronto, ON'

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="http")
#location = geolocator.geocode("175 5th Avenue NYC")
#geolocator = Nominatim()
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print(f'The geograpical coordinate of', address, 'are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Toronto, ON are 43.6534817, -79.3839347.

In [37]:
data_west = data_df[data_df['Borough'].str.contains('West Toronto')].reset_index(drop=True)
data_west

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M6H,West Toronto,"Dufferin, Dovercourt Village",43.669005,-79.442259
1,M6J,West Toronto,"Little Portugal, Trinity",43.647927,-79.419750
2,M6K,West Toronto,"Brockton, Parkdale Village, Exhibition Place",43.636847,-79.428191
3,M6P,West Toronto,"High Park, The Junction South",43.661608,-79.464763
4,M6R,West Toronto,"Parkdale, Roncesvalles",43.648960,-79.456325
5,M6S,West Toronto,"Runnymede, Swansea",43.651571,-79.484450

In [38]:
data_east = data_df[data_df['Borough'].str.contains('East Toronto')].reset_index(drop=True)
data_east

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M4E,East Toronto,The Beaches,43.676357,-79.293031
1,M4K,East Toronto,"The Danforth West, Riverdale",43.679557,-79.352188
2,M4L,East Toronto,"India Bazaar, The Beaches West",43.668999,-79.315572
3,M4M,East Toronto,Studio District,43.659526,-79.340923
4,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",43.662744,-79.321558

In [46]:
# create map of Toronto using latitude and longitude values
map_west = folium.Map(location=[latitude, longitude], zoom_start=13)

# add markers to map
for lat, lng, borough, neighborhood in zip(data_west['Latitude'],
                                           data_west['Longitude'],
                                           data_west['Borough'],
                                           data_west['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_west)  
    
map_west

In [47]:
# create map of Toronto using latitude and longitude values
map_east = folium.Map(location=[latitude, longitude], zoom_start=13)

# add markers to map
for lat, lng, borough, neighborhood in zip(data_east['Latitude'],
                                           data_east['Longitude'],
                                           data_east['Borough'],
                                           data_east['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_east)  
    
map_east

In [63]:
# @hidden_cell
CLIENT_ID = 'hidden' # your Foursquare ID
CLIENT_SECRET = 'hidden' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 50000

In [49]:
data_east.loc[0, 'Neighborhood']

'The Beaches'

In [50]:
data_west.loc[0, 'Neighborhood']

'Dufferin, Dovercourt Village'

In [51]:
neighborhood_latitude_east = data_east.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude_east = data_east.loc[0, 'Longitude'] # neighborhood longitude value

neighborhood_name_east = data_east.loc[0, 'Neighborhood'] # neighborhood name

print('Latitude and longitude values of {} are {}, {}.'.format(neighborhood_name_east, 
                                                               neighborhood_latitude_east, 
                                                               neighborhood_longitude_east))

Latitude and longitude values of The Beaches are 43.67635739999999, -79.2930312.

In [52]:
neighborhood_latitude_west = data_west.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude_west = data_west.loc[0, 'Longitude'] # neighborhood longitude value

neighborhood_name_west = data_west.loc[0, 'Neighborhood'] # neighborhood name

print('Latitude and longitude values of {} are {}, {}.'.format(neighborhood_name_west, 
                                                               neighborhood_latitude_west, 
                                                               neighborhood_longitude_west))

Latitude and longitude values of Dufferin, Dovercourt Village are 43.66900510000001, -79.4422593.

In [59]:
LIMIT = 100
radius = 1000

url_4s_east = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude_east, 
    neighborhood_longitude_east, 
    radius, 
    LIMIT)

In [60]:
LIMIT = 100
radius = 1000

url_4s_west = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude_west, 
    neighborhood_longitude_west, 
    radius, 
    LIMIT)

In [57]:
results_east = requests.get(url_4s_east).json()

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']
    
venues_east = results_east['response']['groups'][0]['items']
nearby_venues_east = json_normalize(venues_east) # flatten JSON
# filter columns
filtered_columns_east = ['venue.name',
                    'venue.categories',
                    'venue.location.lat',
                    'venue.location.lng']
nearby_venues_east =nearby_venues_east.loc[:, filtered_columns_east]
# filter the category for each row
nearby_venues_east['venue.categories'] = nearby_venues_east.apply(get_category_type, axis=1)
# clean columns
nearby_venues_east.columns = [col.split(".")[-1] for col in nearby_venues_east.columns]
nearby_venues_east

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  app.launch_new_instance()

,name,categories,lat,lng
0,Glen Manor Ravine,Trail,43.676821,-79.293942
1,Tori's Bakeshop,Vegetarian / Vegan Restaurant,43.672114,-79.290331
2,The Fox Theatre,Indie Movie Theater,43.672801,-79.287272
3,Beaches Bake Shop,Bakery,43.680363,-79.289692
4,The Beech Tree,Gastropub,43.680493,-79.288846
5,Ed's Real Scoop,Ice Cream Shop,43.672630,-79.287993
6,Veloute Bistro,French Restaurant,43.672267,-79.289584
7,Bagels On Fire,Bagel Shop,43.672864,-79.286784
8,Mastermind Toys,Toy / Game Store,43.671453,-79.293971
9,The Big Carrot Natural Food Market,Health Food Store,43.678879,-79.297734
10,The Remarkable Bean,Coffee Shop,43.672801,-79.287038
11,Beacher Cafe,Breakfast Spot,43.671938,-79.291238
12,The Feathers Pub,Pub,43.680501,-79.287522
13,Kew Gardens,Park,43.669038,-79.298538
14,I'm On The Beach,Beach,43.670364,-79.284696
15,Xola,Mexican Restaurant,43.672603,-79.288080
16,Balmy Beach,Beach,43.668169,-79.291355
17,Green Eggplant,Mediterranean Restaurant,43.670517,-79.298660
18,The Ten Spot,Nail Salon,43.670340,-79.299363
19,Isabellaâ€™s Boutique Restaurant,Japanese Restaurant,43.673767,-79.282703
20,Castro's Lounge,Bar,43.671104,-79.295107
21,Sanna's Farmacia,Juice Bar,43.670929,-79.295969
22,Vi Vetha,Breakfast Spot,43.673720,-79.282155
23,The Fill Station,Pub,43.673256,-79.284943
24,Kew Gardens Play Park,Park,43.669267,-79.299684
25,Yumei Sushi,Japanese Restaurant,43.671108,-79.295064
26,Life Is Sweet,Cupcake Shop,43.673739,-79.282613
27,LCBO,Liquor Store,43.669993,-79.300383
28,Sunset Grill,Diner,43.670214,-79.299653
29,Pippins Tea Company,Tea Room,43.670992,-79.295905
30,Delhi Bistro,Indian Restaurant,43.672506,-79.288353
31,Green Basil,Thai Restaurant,43.671200,-79.294717
32,Cool Runnings,Caribbean Restaurant,43.683497,-79.300017
33,The Green Dragon,Pub,43.680834,-79.284712
34,The Real Jerk Beaches,Caribbean Restaurant,43.680781,-79.285727
35,No Bull Burger,Burger Joint,43.680761,-79.285019
36,Subway,Sandwich Place,43.670812,-79.295526
37,COBS Bread,Bakery,43.669881,-79.300828
38,Foodland - Toronto,Grocery Store,43.670736,-79.298267
39,Kyouka Ramen,Ramen Restaurant,43.672574,-79.287992
40,Grinder,Coffee Shop,43.683073,-79.299875
41,Shoppers Drug Mart,Pharmacy,43.670639,-79.297690
42,The Nutty Chocolatier,Chocolate Shop,43.670567,-79.297598
43,Grover Pub and Grub,Pub,43.679181,-79.297215
44,Outrigger Tap & Table,Pub,43.672761,-79.287764
45,Juice and Java,CafÃ©,43.671062,-79.295755
46,Bikkuri Japanese Restaurant,Japanese Restaurant,43.670715,-79.296956
47,The Goof,Asian Restaurant,43.672633,-79.287467
48,Pizza Hut,Pizza Place,43.670789,-79.296840
49,Souvlaki Hut,Greek Restaurant,43.671048,-79.295758
50,Tim Hortons,Coffee Shop,43.670286,-79.299733
51,Tim Hortons,Coffee Shop,43.680799,-79.282907
52,Gabby's Food & Fuel,Bar,43.670809,-79.296657
53,The Beer Store,Beer Store,43.680439,-79.282600
54,Garden Gate Resturant,Breakfast Spot,43.672615,-79.287492
55,Subway,Sandwich Place,43.680716,-79.287006
56,Pizza Pizza,Pizza Place,43.680899,-79.283878
57,TD Canada Trust,Bank,43.670843,-79.297956
58,Hero Certified Burgers,Burger Joint,43.670360,-79.298924
59,Seaspray Restaurant,Asian Restaurant,43.678888,-79.298167
60,Divine Gelato Lounge and Coffee Bar,Dessert Shop,43.671422,-79.293281
61,Starbucks,Coffee Shop,43.680880,-79.284970
62,The Dog Market,Pet Store,43.671163,-79.294773
63,Dyson's valu-mart,Grocery Store,43.673271,-79.285854
64,Tails,Pet Store,43.670762,-79.296424
65,Trinity Gallery,Furniture / Home Store,43.682153,-79.289363
66,The Salty Dog,Restaurant,43.669944,-79.300894
67,Scarboro Beach,Beach,43.669273,-79.293902
68,SUPgirlz,Scenic Lookout,43.668989,-79.290476
69,Star of Kingston Road,Pizza Place,43.676888,-79.303975
70,Wing Machine,Pizza Place,43.680845,-79.283787
71,Fiorio Beaches,Salon / Barbershop,43.669913,-79.300529
72,Running Room,Sporting Goods Shop,43.669736,-79.300405
73,Little Elf House Under A Tree,Tree,43.668419,-79.297492
74,Lower Victoria Park,Plaza,43.683075,-79.285191
75,The Artisans,Jewelry Store,43.669760,-79.301167
76,Pizzaville,Pizza Place,43.669704,-79.301244
77,The Beach Mall,Shopping Mall,43.669631,-79.301247

In [61]:
results_west = requests.get(url_4s_west).json()

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']
    
venues_west = results_west['response']['groups'][0]['items']
nearby_venues_west = json_normalize(venues_west) # flatten JSON
# filter columns
filtered_columns_west = ['venue.name',
                    'venue.categories',
                    'venue.location.lat',
                    'venue.location.lng']
nearby_venues_west =nearby_venues_west.loc[:, filtered_columns_west]
# filter the category for each row
nearby_venues_west['venue.categories'] = nearby_venues_west.apply(get_category_type, axis=1)
# clean columns
nearby_venues_west.columns = [col.split(".")[-1] for col in nearby_venues_west.columns]
nearby_venues_west

KeyError: 'groups'

In [ ]:
nearby_venues_west.shape

In [ ]:
print('East Toronto has {} venus,'.format(nearby_venues_east.shape[0]), 'and West Toronto has {} venus.'.format(nearby_venues_west.shape[0]))

In [ ]:
def getNearbyVenues_east(names, latitudes, longitudes, radius=1000):
    
    venues_list_east=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)

        url_4s1_east = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)

        results_east = requests.get(url_4s1_east).json()["response"]['groups'][0]['items']

        venues_list_east.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results_east])

    nearby_venues_east = pd.DataFrame([item for venues_list_east in venues_list_east for item in venues_list_east])
    nearby_venues_east.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues_east)

In [ ]:
def getNearbyVenues_west(names, latitudes, longitudes, radius=1000):
    
    venues_list_west=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)

        url_4s1_west = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)

        results_west = requests.get(url_4s1_west).json()["response"]['groups'][0]['items']

        venues_list_west.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results_west])

    nearby_venues_west = pd.DataFrame([item for venues_list_west in venues_list_west for item in venues_list_west])
    nearby_venues_west.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues_west)

In [ ]:
toronto_venues_east = getNearbyVenues_east(names=data_east['Neighborhood'],
                                   latitudes=data_east['Latitude'],
                                   longitudes=data_east['Longitude']
                                  )

In [ ]:
toronto_venues_west = getNearbyVenues_west(names=data_west['Neighborhood'],
                                   latitudes=data_west['Latitude'],
                                   longitudes=data_west['Longitude']
                                  )

In [ ]:
toronto_venues_east

In [ ]:
toronto_venues_west

In [ ]:
toronto_venues_east.groupby('Neighborhood').count()
print('There are {} uniques categories.'.format(len(toronto_venues_east['Venue Category'].unique())))

In [ ]:
toronto_venues_west.groupby('Neighborhood').count()
print('There are {} uniques categories.'.format(len(toronto_venues_west['Venue Category'].unique())))

In [ ]:
# one hot encoding
toronto_onehot_east = pd.get_dummies(toronto_venues_east[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
toronto_onehot_east['Neighborhood'] = toronto_venues_east['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns_east = [toronto_onehot_east.columns[-1]] + list(toronto_onehot_east.columns[:-1])
toronto_onehot_east = toronto_onehot_east[fixed_columns_east]

toronto_onehot_east

In [ ]:
# one hot encoding
toronto_onehot_west = pd.get_dummies(toronto_venues_west[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
toronto_onehot_west['Neighborhood'] = toronto_venues_west['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns_west = [toronto_onehot_west.columns[-1]] + list(toronto_onehot_west.columns[:-1])
toronto_onehot_west = toronto_onehot_west[fixed_columns_west]

toronto_onehot_west

In [ ]:
toronto_grouped_east = toronto_onehot_east.groupby('Neighborhood').mean().reset_index()
num_top_venues_east = 5

for hood in toronto_grouped_east['Neighborhood']:
    print("----"+hood+"----")
    temp = toronto_grouped_east[toronto_grouped_east['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues_east))
    print('\n')

In [ ]:
toronto_grouped_west = toronto_onehot_west.groupby('Neighborhood').mean().reset_index()
num_top_venues_west = 5

for hood in toronto_grouped_west['Neighborhood']:
    print("----"+hood+"----")
    temp = toronto_grouped_west[toronto_grouped_west['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues_west))
    print('\n')

In [ ]:
def return_most_common_venues_east(row, num_top_venues_east):
    row_categories_east = row.iloc[1:]
    row_categories_sorted_east = row_categories_east.sort_values(ascending=False)
    
    return row_categories_sorted_east.index.values[0:num_top_venues_east]

In [ ]:
def return_most_common_venues_west(row, num_top_venues_west):
    row_categories_west = row.iloc[1:]
    row_categories_sorted_west = row_categories_west.sort_values(ascending=False)
    
    return row_categories_sorted_west.index.values[0:num_top_venues_west]

In [ ]:
num_top_venues_east = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues_east):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted_east = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted_east['Neighborhood'] = toronto_grouped_east['Neighborhood']

for ind in np.arange(toronto_grouped_east.shape[0]):
    neighborhoods_venues_sorted_east.iloc[ind, 1:] = return_most_common_venues_east(toronto_grouped_east.iloc[ind, :], num_top_venues_east)

neighborhoods_venues_sorted_east

In [ ]:
num_top_venues_west = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues_west):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted_west = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted_west['Neighborhood'] = toronto_grouped_west['Neighborhood']

for ind in np.arange(toronto_grouped_west.shape[0]):
    neighborhoods_venues_sorted_west.iloc[ind, 1:] = return_most_common_venues_west(toronto_grouped_west.iloc[ind, :], num_top_venues_west)

neighborhoods_venues_sorted_west

In [ ]:
kclusters = 5

toronto_grouped_clustering_east = toronto_grouped_east.drop('Neighborhood', 1)

kmeans_east = KMeans(n_clusters=kclusters, random_state=0).fit(toronto_grouped_clustering_east)

kmeans_east.labels_[0:10]

In [ ]:
kclusters = 5

toronto_grouped_clustering_west = toronto_grouped_west.drop('Neighborhood', 1)

kmeans_west = KMeans(n_clusters=kclusters, random_state=0).fit(toronto_grouped_clustering_west)

kmeans_west.labels_[0:10]

In [ ]:
toronto_merged_east = data_east

toronto_merged_east['Cluster Labels'] = kmeans_east.labels_

toronto_merged_east = toronto_merged_east.join(neighborhoods_venues_sorted_east.set_index('Neighborhood'), on='Neighborhood')

toronto_merged_east.head()

In [ ]:
toronto_merged_west = data_west

toronto_merged_west['Cluster Labels'] = kmeans_west.labels_

toronto_merged_west = toronto_merged_west.join(neighborhoods_venues_sorted_west.set_index('Neighborhood'), on='Neighborhood')

toronto_merged_west.head()

In [ ]:
map_clusters_east = folium.Map(location=[latitude, longitude], zoom_start=13)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged_east['Latitude'],
                                  toronto_merged_east['Longitude'],
                                  toronto_merged_east['Neighborhood'],
                                  toronto_merged_east['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters_east)
       
map_clusters_east

In [ ]:
map_clusters_west = folium.Map(location=[latitude, longitude], zoom_start=13)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged_west['Latitude'],
                                  toronto_merged_west['Longitude'],
                                  toronto_merged_west['Neighborhood'],
                                  toronto_merged_west['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters_west)
       
map_clusters_west

In [ ]:
toronto_east_group = toronto_venues_east.groupby('Venue Category').count()
print('There are {} uniques categories.'.format(len(toronto_venues_east['Venue Category'].unique())))

In [ ]:
toronto_west_group = toronto_venues_west.groupby('Venue Category').count()
print('There are {} uniques categories.'.format(len(toronto_venues_west['Venue Category'].unique())))

In [ ]:
toronto_east_group.sort_values(by='Neighborhood', ascending=True, inplace=True)

df_top10_east = toronto_east_group['Neighborhood'].tail(10)
df_top10_east

In [ ]:
toronto_west_group.sort_values(by='Neighborhood', ascending=True, inplace=True)

df_top10_west = toronto_west_group['Neighborhood'].tail(10)
df_top10_west

In [ ]:
df_top10_east.plot(kind='barh', figsize=(12, 12), color='limegreen')
plt.xlabel('Kind of Shops')
plt.title('Top 15 kind of shops in Totonto - East')

plt.show()

In [ ]:
df_top10_west.plot(kind='barh', figsize=(12, 12), color='orange')
plt.xlabel('Kind of Shops')
plt.title('Top 15 kind of shops in Totonto - West')

plt.show()